### ISSUE TITLE
[Bug]: Only the last couple of days are shown (with workaround)

### ISSUE THREAD

**Issue by hmijail** [Quorafind/Obsidian-Daily-Notes-Editor#40]
### Bug Description

When I open the plugin's view, only the last couple of days' notes are shown.

### Relevant Screenshot

https://github.com/Quorafind/Obsidian-Daily-Notes-Editor/assets/4139546/d67d0c3c-b723-4e95-b94d-7c9120023ef4

### To Reproduce

To reproduce just create a couple of **short** notes in the latest dates and open the plugin's view.

But I think I found the reason and a workaround: if the shown note/s are too short to cause the scrollbar to appear, then no more notes are included in the view.

The workaround then is to change the size of the window momentarily, making it narrow, so that the text gets flowed down the available space. Once the scrollbar appears, the rest of notes will be populated. At that point you can resize the window back to your preferred size and the viewer keeps working correctly.

This is probably related to #37 .

### Obsidian Version

1.5.12

### Which plugin are you using for daily notes?

- [X] Default Daily Note Plugin
- [ ] Periodic Notes Plugin

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Please check if this issue remains in 0.1.6

**Comment by hmijail** [comment]
Seems to be fixed, thank you!

**Comment by hmijail** [comment]
Sorry, I am finding the issue is actually still there, only less frequent. Not sure yet what exactly triggers the problem, so I haven't found a way to reproduce it reliably.

**Comment by calvinwyoung** [comment]
FYI the version linked in this comment fixes the issue for me:
https://github.com/Quorafind/Obsidian-Daily-Notes-Editor/pull/41#discussion_r1653018811

**Comment by hmijail** [comment]
@calvinwyoung I installed it and will report back.
But for starters, looks like this version ignores the settings to not show backlinks and unlinked mentions.

**Comment by hmijail** [comment]
@calvinwyoung now somehow the settings for backlinks and unlinked mentions do work. No idea of what changed, hopefully it was my mistake. 

Anyway, your version seems to work better than the original one, but still it's easy to make it fail: open the Daily Note view, quit Obsidian, and start it again. In this case the Daily Note view only shows 2 dates. Pressing the Daily Note button causes the view to be refreshed correctly. 

Not sure if this is the same bug or a different one?

**Comment by Knuckles92** [comment]
I have this same issue(only loads 2-3 notes when i first click the icon). I am able to get all of them to show by just switching from the Daily Notes Editor tab, to any other tab, then switching back to the Daily Notes Editor tab. 

Any updates to fix this would be great. Thank you so much!

**Comment by Quorafind** [comment]
Could you take a look at 0.1.7 and see if this issue remains?

**Comment by hmijail** [comment]
Tried 0.1.7. If the Daily Note tab exists when Obsidian is started, its content is bad: it either contains 1 or 2 days.
I always have to press the "Open Daily Note Editor" button to make the tab be filled correctly.

**Comment by questmaster** [comment]
After playing around a bit I see the same behaviour as @hmijail.
I can confim that new Journal entries are loaded in the background, eg. if you resize the window. But the UI seems not to respond and when hovering the cursor over the stuck content I got a small notice (censored the stuff unter the black square):
![image](https://github.com/Quorafind/Obsidian-Daily-Notes-Editor/assets/606327/323f6949-04c0-46c2-9509-0514f25d5857)

Maybe this helps in further investigation...

**Comment by RaphZufferey** [comment]
Same issue here, on version 0.1.7.
Really loving the plugin otherwise

**Comment by Quorafind** [comment]
> After playing around a bit I see the same behaviour as @hmijail. I can confim that new Journal entries are loaded in the background, eg. if you resize the window. But the UI seems not to respond and when hovering the cursor over the stuck content I got a small notice (censored the stuff unter the black square): ![image](https://private-user-images.githubusercontent.com/606327/346090585-323f6949-04c0-46c2-9509-0514f25d5857.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTA0NjIsIm5iZiI6MTcyMTAxMDE2MiwicGF0aCI6Ii82MDYzMjcvMzQ2MDkwNTg1LTMyM2Y2OTQ5LTA0YzAtNDZjMi05NTA5LTA1MTRmMjVkNTg1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwMjIyNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjRlOTI4YTRhOGFkMTQ1NjkxODIxNjBiM2Q1ZDliMTZjYTUzMzUwNTEyY2MyMjBmNzNmZWFiMzA3ZmYxNjE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.enHxVJ_U_xty9XWebPBdw_s5UgrKaAPJqou3tX5qAOo)
> 
> Also it seems that the 'create Journal Entry' section overlaps the underlying page header. Maybe this helps in further investigation...

Thanks!

**Comment by Quorafind** [comment]
Could you please try the lastest version? 0.1.8

**Comment by RaphZufferey** [comment]
Version 0.1.8 seems to have fixed it for me! Thank you very much, this is super helpful.

**Comment by hmijail** [comment]
FWIW, after a couple of days trying it, I was about to report that 0.18 still fails in the same way for me... but I tried just once more and now it works?? I'll keep an eye on it.

Anyway, did the ribbon button's icon change on purpose? Now it's a small calendar sheet, which to me is easy to mistake for other small calendar / small rectangle icons (4 in my case). The original purple icon remains in the Daily Note tab though, so I wonder if the change was by mistake.

**Comment by hmijail** [comment]
I don't remember seeing this exact issue again, so I will close now.
